name: Recipe
displayField: Item{Result}
fields:
  - name: RequiredQuality
  - name: Quest
    type: link
    targets: [Quest]
  - name: Number
  - name: CraftType
    type: link
    targets: [CraftType]
  - name: ItemResult
    type: link
    targets: [Item]
  - name: Ingredient
    type: array
    count: 8
    fields:
      - type: link
        targets: [Item]
  - name: StatusRequired
    type: link
    targets: [Status]
  - name: ItemRequired
    type: link
    targets: [Item]
  - name: RecipeLevelTable
    type: link
    targets: [RecipeLevelTable]
  - name: RecipeNotebookList
    type: link
    targets: [RecipeNotebookList]
  - name: DisplayPriority
  - name: DifficultyFactor
  - name: QualityFactor
  - name: DurabilityFactor
  - name: RequiredCraftsmanship
  - name: RequiredControl
  - name: QuickSynthCraftsmanship
  - name: QuickSynthControl
  - name: Unknown0
  - name: SecretRecipeBook
    type: link
    targets: [SecretRecipeBook]
  - name: CollectableMetadata
    type: link
    condition:
      switch: CollectableMetadataKey
      cases:
        1: [CollectablesShopRefine]
        2: [HWDCrafterSupply]
        3: [SatisfactionSupply]
        4: [SharlayanCraftWorksSupply]
        6: [CollectablesRefine] # For Wachumeqimeqi (Banka) deliveries
  - name: PatchNumber
  - name: AmountResult
  - name: AmountIngredient
    type: array
    count: 8
  - name: MaterialQualityFactor
  - name: CollectableMetadataKey
  - name: IsSecondary
  - name: CanQuickSynth
  - name: CanHq
  - name: ExpRewarded
  - name: IsSpecializationRequired
  - name: IsExpert
  - name: Unknown1
